version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "money-api"
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
